import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PortalWrap from "@/components/PortalWrap/PortalWrap";
import Toast from "@/components/Toast/Toast";
import { MSWComponent } from "@/libs/MSWComponent/MSWComponent";
import SSRQueryClientProvider from "@/libs/ReactQuery/SSRQueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SSRQueryClientProvider>
          <MSWComponent />
          {children}
          <PortalWrap />
          <Toast />
        </SSRQueryClientProvider>
      </body>
    </html>
  );
}
